# Generated by Django 5.2.8 on 2025-11-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('AN', 'Anillo'), ('CO', 'Collar'), ('PU', 'Pulsera'), ('AR', 'Aretes')], default='AN', max_length=2)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='joyas/')),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
    ]
