# Generated by Django 5.2.8 on 2025-11-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_orden_detalleorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ciudad',
            field=models.CharField(default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='orden',
            name='codigo_postal',
            field=models.CharField(default='', max_length=20, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion',
            field=models.CharField(default='', max_length=250, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
