# Generated by Django 5.2.8 on 2025-11-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_orden_ciudad_orden_codigo_postal_orden_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, verbose_name='¿Está en Oferta?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Rebajado'),
        ),
    ]
