# Generated by Django 5.2.8 on 2025-11-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_orden_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: VERANO2025', max_length=50, unique=True)),
                ('descuento', models.IntegerField(help_text='Porcentaje de descuento (0-100)')),
                ('valido_desde', models.DateTimeField()),
                ('valido_hasta', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
