# Generated by Django 5.2.8 on 2025-11-30 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='usuarios_usados',
            field=models.ManyToManyField(blank=True, related_name='cupones_usados', to=settings.AUTH_USER_MODEL),
        ),
    ]
