# Generated by Django 5.2.8 on 2025-12-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_categoria_alter_producto_categoria_variante'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.variante'),
        ),
    ]
