"""
Django settings for tormenta project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


print("--- INICIO DE DIAGNÓSTICO ---")
env_path = BASE_DIR / '.env'
print(f"Buscando archivo .env en: {env_path}")
print(f"¿Existe el archivo?: {env_path.exists()}")

load_dotenv(BASE_DIR / '.env')
load_dotenv(env_path)
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = os.getenv('DEBUG', 'False').strip() == 'True'

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tienda',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'tormenta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tormenta.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
   'default': {
       'ENGINE': 'django.db.backends.postgresql',
       'NAME': 'angel_wings_db',
       'USER': 'postgres',       
       'PASSWORD': 'Mar1@nela',
       'HOST': 'localhost',
       'PORT': '5432',
   }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de Archivos Multimedia (Fotos)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
SITE_ID = 2

# Cierra la sesión si el usuario cierra el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Impide que Javascript pueda leer las cookies de sesión
SESSION_COOKIE_HTTPONLY = False
CSRF_COOKIE_HTTPONLY = False
# Esta lógica detecta si DEBUG es False (Producción) para activar el modo estricto
if not DEBUG:
    # Solo enviar cookies si la conexión es segura (HTTPS)
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    
    # Obligar a los navegadores a usar HTTPS por un tiempo largo (HSTS)
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000 # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Evita que el navegador adivine tipos de contenido (Sniffing)
    SECURE_CONTENT_TYPE_NOSNIFF = True

# 'DENY': Bloquea que tu sitio se cargue en cualquier iframe (Más seguro).
# 'SAMEORIGIN': Permite iframes solo si vienen de tu mismo dominio.
X_FRAME_OPTIONS = 'DENY'

CSP_DEFAULT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", "fonts.googleapis.com", "cdn.jsdelivr.net")
CSP_SCRIPT_SRC = ("'self'", "cdn.jsdelivr.net")
CSP_IMG_SRC = ("'self'", "data:", "images.unsplash.com")
CSP_FONT_SRC = ("'self'", "fonts.gstatic.com", "cdn.jsdelivr.net")

# Reemplazar con dominio real cuando haga deploy
CSRF_TRUSTED_ORIGINS = ['https://tormentajoyas.onrender.com']

AXES_FAILURE_LIMIT = 2
AXES_COOLOFF_TIME = 1 # Horas de bloqueo

AUTHENTICATION_BACKENDS = [
    # 1. El sistema por defecto de Django (para que el login normal siga funcionando)
    'django.contrib.auth.backends.ModelBackend',

    # 2. El sistema de Axes (para vigilar los intentos fallidos)
    'axes.backends.AxesStandaloneBackend',
]